/* 상품테이블 */
CREATE TABLE PRODUCT (
	PRODUCT_ID VARCHAR2(10) NOT NULL, /* 상품ID */
	PTNR_ID VARCHAR2(10) NOT NULL, /* 파트너ID */
	PRODUCT_NM VARCHAR2(200), /* 상품이름 */
	CTGR_1ST VARCHAR2(6) NOT NULL, /* 대분류 */
	CTGR_2ND VARCHAR2(6) NOT NULL, /* 중분류 */
	CTGR_3RD VARCHAR2(6) NOT NULL, /* 소분류 */
	SALES_COST NUMBER, /* 판매가격 */
	CMNT VARCHAR2(2000) /* 코멘트 */
);

COMMENT ON TABLE PRODUCT IS '상품테이블';

COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품ID';

COMMENT ON COLUMN PRODUCT.PTNR_ID IS '파트너ID';

COMMENT ON COLUMN PRODUCT.PRODUCT_NM IS '상품이름';

COMMENT ON COLUMN PRODUCT.CTGR_1ST IS '대분류';

COMMENT ON COLUMN PRODUCT.CTGR_2ND IS '중분류';

COMMENT ON COLUMN PRODUCT.CTGR_3RD IS '소분류';

COMMENT ON COLUMN PRODUCT.SALES_COST IS '판매가격';

COMMENT ON COLUMN PRODUCT.CMNT IS '코멘트';

CREATE UNIQUE INDEX PK_PRODUCT
	ON PRODUCT (
		PRODUCT_ID ASC
	);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT PK_PRODUCT
		PRIMARY KEY (
			PRODUCT_ID
		);

/* 재고 */
CREATE TABLE STOCK (
	PRODUCT_ID VARCHAR2(10) NOT NULL, /* 상품ID */
	STOCK NUMBER NOT NULL, /* 재고 */
	SAFETY_STOCK NUMBER NOT NULL, /* 안전재고 */
	UNIT_PRICE NUMBER NOT NULL /* 단가 */
);

COMMENT ON TABLE STOCK IS '재고';

COMMENT ON COLUMN STOCK.PRODUCT_ID IS '상품ID';

COMMENT ON COLUMN STOCK.STOCK IS '재고';

COMMENT ON COLUMN STOCK.SAFETY_STOCK IS '안전재고';

COMMENT ON COLUMN STOCK.UNIT_PRICE IS '단가';

CREATE UNIQUE INDEX PK_STOCK
	ON STOCK (
		PRODUCT_ID ASC
	);

ALTER TABLE STOCK
	ADD
		CONSTRAINT PK_STOCK
		PRIMARY KEY (
			PRODUCT_ID
		);

/* 판매 테이블 */
CREATE TABLE ORDR (
	ORDR_ID VARCHAR2(20) NOT NULL, /* 주문ID */
	PRODUCT_ID VARCHAR2(10) NOT NULL, /* 상품ID */
	PTNR_ID VARCHAR2(10) NOT NULL, /* 파트너ID */
	UNIT_PRICE NUMBER, /* 당시단가 */
	SALES_COST NUMBER, /* 당시가격 */
	AMNT NUMBER NOT NULL, /* 수량 */
	AMNT_LO NUMBER NOT NULL, /* 남은수량 */
	ORDR_DATE DATE, /* 주문시간 */
	CONFIRM_DATE DATE, /* 승인시간 */
	STATUS VARCHAR2(4), /* 주문상태 */
	SUM NUMBER, /* 합계 */
	CMNT VARCHAR2(2000) /* 코멘트 */
);

COMMENT ON TABLE ORDR IS '판매 테이블';

COMMENT ON COLUMN ORDR.ORDR_ID IS '주문ID';

COMMENT ON COLUMN ORDR.PRODUCT_ID IS '상품ID';

COMMENT ON COLUMN ORDR.PTNR_ID IS '파트너ID';

COMMENT ON COLUMN ORDR.UNIT_PRICE IS '판매당시단가';

COMMENT ON COLUMN ORDR.SALES_COST IS '판매당시가격';

COMMENT ON COLUMN ORDR.AMNT IS '수량';

COMMENT ON COLUMN ORDR.AMNT_LO IS '남은수량';

COMMENT ON COLUMN ORDR.ORDR_DATE IS '주문시간';

COMMENT ON COLUMN ORDR.CONFIRM_DATE IS '승인시간';

COMMENT ON COLUMN ORDR.STATUS IS 'CODE999';

COMMENT ON COLUMN ORDR.SUM IS '합계';

COMMENT ON COLUMN ORDR.CMNT IS '코멘트';

CREATE UNIQUE INDEX PK_ORDR
	ON ORDR (
		ORDR_ID ASC,
		PRODUCT_ID ASC
	);

ALTER TABLE ORDR
	ADD
		CONSTRAINT PK_ORDR
		PRIMARY KEY (
			ORDR_ID,
			PRODUCT_ID
		);

/* 출고 테이블 */
CREATE TABLE OUTGOING (
	ORDR_ID VARCHAR2(20) NOT NULL, /* 주문ID */
	PRODUCT_ID VARCHAR2(10) NOT NULL, /* 상품ID */
	COUNT NUMBER NOT NULL, /* 출고차수 */
	AMNT NUMBER, /* 출고수량 */
	OG_DATE DATE /* 출고시간 */
);

COMMENT ON TABLE OUTGOING IS '출고 테이블';

COMMENT ON COLUMN OUTGOING.ORDR_ID IS '주문ID';

COMMENT ON COLUMN OUTGOING.PRODUCT_ID IS '상품ID';

COMMENT ON COLUMN OUTGOING.COUNT IS '출고차수';

COMMENT ON COLUMN OUTGOING.AMNT IS '출고수량';

COMMENT ON COLUMN OUTGOING.OG_DATE IS '출고시간';

CREATE UNIQUE INDEX PK_OUTGOING
	ON OUTGOING (
		ORDR_ID ASC,
		PRODUCT_ID ASC,
		COUNT ASC
	);

ALTER TABLE OUTGOING
	ADD
		CONSTRAINT PK_OUTGOING
		PRIMARY KEY (
			ORDR_ID,
			PRODUCT_ID,
			COUNT
		);

/* 발주 테이블 */
CREATE TABLE PURCHASE (
	PURCHASE_ID VARCHAR2(20) NOT NULL, /* 주문ID */
	PRODUCT_ID VARCHAR2(10) NOT NULL, /* 상품ID */
	UNIT_PRICE NUMBER NOT NULL, /* 발주단가 */
	AMNT NUMBER NOT NULL, /* 발주수량 */
	AMNT_LO NUMBER, /* 남은수량 */
	PURCHASE_DATE DATE, /* 발주시간 */
	CONFIRM_DATE DATE, /* 승인시간 */
	STATUS VARCHAR2(4), /* 현재상태 */
	ETA DATE, /* 예상도착시간 */
	ORDR_SUM NUMBER, /* 합계 */
	CMNT VARCHAR2(2000) /* 코멘트 */
);

COMMENT ON TABLE PURCHASE IS '발주 테이블';

COMMENT ON COLUMN PURCHASE.PURCHASE_ID IS '주문ID';

COMMENT ON COLUMN PURCHASE.PRODUCT_ID IS '상품ID';

COMMENT ON COLUMN PURCHASE.UNIT_PRICE IS '발주단가';

COMMENT ON COLUMN PURCHASE.AMNT IS '발주수량';

COMMENT ON COLUMN PURCHASE.AMNT_LO IS '남은수량';

COMMENT ON COLUMN PURCHASE.PURCHASE_DATE IS '발주시간';

COMMENT ON COLUMN PURCHASE.CONFIRM_DATE IS '승인시간';

COMMENT ON COLUMN PURCHASE.STATUS IS 'CODE999';

COMMENT ON COLUMN PURCHASE.ETA IS '예상도착시간';

COMMENT ON COLUMN PURCHASE.ORDR_SUM IS '합계';

COMMENT ON COLUMN PURCHASE.CMNT IS '코멘트';

CREATE UNIQUE INDEX PK_PURCHASE
	ON PURCHASE (
		PURCHASE_ID ASC
	);

ALTER TABLE PURCHASE
	ADD
		CONSTRAINT PK_PURCHASE
		PRIMARY KEY (
			PURCHASE_ID
		);

/* 입고 테이블 */
CREATE TABLE INCOMING (
	PURCHASE_ID VARCHAR2(20) NOT NULL, /* 주문ID */
	COUNT NUMBER NOT NULL, /* 입고차수 */
	AMNT NUMBER, /* 입고수량 */
	IC_DATE DATE /* 입고날짜 */
);

COMMENT ON TABLE INCOMING IS '입고 테이블';

COMMENT ON COLUMN INCOMING.PURCHASE_ID IS '주문ID';

COMMENT ON COLUMN INCOMING.COUNT IS '입고차수';

COMMENT ON COLUMN INCOMING.AMNT IS '입고수량';

COMMENT ON COLUMN INCOMING.IC_DATE IS '입고날짜';

CREATE UNIQUE INDEX PK_INCOMING
	ON INCOMING (
		PURCHASE_ID ASC,
		COUNT ASC
	);

ALTER TABLE INCOMING
	ADD
		CONSTRAINT PK_INCOMING
		PRIMARY KEY (
			PURCHASE_ID,
			COUNT
		);

/* 파트너사 */
CREATE TABLE PARTNER (
	PTNR_ID VARCHAR2(10) NOT NULL, /* 파트너ID */
	PTNR_NM VARCHAR2(200) NOT NULL, /* 회사명 */
	PTNR_NM_ENG VARCHAR2(200), /* 회사영문명 */
	REGISTER_NO VARCHAR2(100), /* 사업자등록번호 */
	TYPE VARCHAR2(4), /* 파트너분류 */
	ADDR VARCHAR2(200), /* 주소 */
	TEL VARCHAR2(30), /* 전화번호 */
	FAX VARCHAR2(30), /* 새 컬럼 */
	CEO_NM VARCHAR2(50), /* 대표이름 */
	CLT_NM VARCHAR2(50), /* 담당자이름 */
	CLT_TEL VARCHAR2(30), /* 담당자번호 */
	CMNT VARCHAR2(2000) /* 코멘트 */
);

COMMENT ON TABLE PARTNER IS '파트너사';

COMMENT ON COLUMN PARTNER.PTNR_ID IS '파트너ID';

COMMENT ON COLUMN PARTNER.PTNR_NM IS '회사명';

COMMENT ON COLUMN PARTNER.PTNR_NM_ENG IS '회사영문명';

COMMENT ON COLUMN PARTNER.REGISTER_NO IS '사업자등록번호';

COMMENT ON COLUMN PARTNER.TYPE IS 'CODE999';

COMMENT ON COLUMN PARTNER.ADDR IS '주소';

COMMENT ON COLUMN PARTNER.TEL IS '전화번호';

COMMENT ON COLUMN PARTNER.FAX IS '새 컬럼';

COMMENT ON COLUMN PARTNER.CEO_NM IS '대표이름';

COMMENT ON COLUMN PARTNER.CLT_NM IS '담당자이름';

COMMENT ON COLUMN PARTNER.CLT_TEL IS '담당자번호';

COMMENT ON COLUMN PARTNER.CMNT IS '코멘트';

CREATE UNIQUE INDEX PK_PARTNER
	ON PARTNER (
		PTNR_ID ASC
	);

ALTER TABLE PARTNER
	ADD
		CONSTRAINT PK_PARTNER
		PRIMARY KEY (
			PTNR_ID
		);

/* 새 테이블8 */
CREATE TABLE c (
);

COMMENT ON TABLE c IS '새 테이블8';

/* 카테고리일람 */
CREATE TABLE CATEGORY (
	CTGR_ID VARCHAR2(6) NOT NULL, /* 카테고리ID */
	CTGR_NM VARCHAR2(200) NOT NULL, /* 카테고리이름 */
	CTGR_PARENT VARCHAR2(6), /* 상위카테고리 */
	CTGR_LVL VARCHAR2(4) NOT NULL /* 카테고리티어 */
);

COMMENT ON TABLE CATEGORY IS '카테고리일람';

COMMENT ON COLUMN CATEGORY.CTGR_ID IS '카테고리ID';

COMMENT ON COLUMN CATEGORY.CTGR_NM IS '카테고리이름';

COMMENT ON COLUMN CATEGORY.CTGR_PARENT IS '상위카테고리';

COMMENT ON COLUMN CATEGORY.CTGR_LVL IS 'CODE999';

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		CTGR_ID ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			CTGR_ID
		);

/* 새 테이블 */
CREATE TABLE CODE999 (
	MAIN_CODE VARCHAR2(50) NOT NULL, /* 현재상태 */
	SUB_CODE VARCHAR2(4) NOT NULL, /* 파트너분류 */
	MAIN_CODE_NM VARCHAR2(50) NOT NULL, /* 카테고리티어 */
	SUB_CODE_NM VARCHAR2(50) NOT NULL, /* 새 컬럼 */
	USE_YN CHAR NOT NULL /* 새 컬럼2 */
);

COMMENT ON TABLE CODE999 IS '새 테이블';

COMMENT ON COLUMN CODE999.MAIN_CODE IS '현재상태';

COMMENT ON COLUMN CODE999.SUB_CODE IS '파트너분류';

COMMENT ON COLUMN CODE999.MAIN_CODE_NM IS '카테고리티어';

COMMENT ON COLUMN CODE999.SUB_CODE_NM IS '새 컬럼';

COMMENT ON COLUMN CODE999.USE_YN IS '새 컬럼2';

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_CATEGORY_TO_PRODUCT
		FOREIGN KEY (
			CTGR_1ST
		)
		REFERENCES CATEGORY (
			CTGR_ID
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_PARTNER_TO_PRODUCT
		FOREIGN KEY (
			PTNR_ID
		)
		REFERENCES PARTNER (
			PTNR_ID
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_CATEGORY_TO_PRODUCT2
		FOREIGN KEY (
			CTGR_2ND
		)
		REFERENCES CATEGORY (
			CTGR_ID
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_CATEGORY_TO_PRODUCT3
		FOREIGN KEY (
			CTGR_3RD
		)
		REFERENCES CATEGORY (
			CTGR_ID
		);

ALTER TABLE STOCK
	ADD
		CONSTRAINT FK_PRODUCT_TO_STOCK
		FOREIGN KEY (
			PRODUCT_ID
		)
		REFERENCES PRODUCT (
			PRODUCT_ID
		);

ALTER TABLE ORDR
	ADD
		CONSTRAINT FK_PRODUCT_TO_ORDR
		FOREIGN KEY (
			PRODUCT_ID
		)
		REFERENCES PRODUCT (
			PRODUCT_ID
		);

ALTER TABLE ORDR
	ADD
		CONSTRAINT FK_PARTNER_TO_ORDR
		FOREIGN KEY (
			PTNR_ID
		)
		REFERENCES PARTNER (
			PTNR_ID
		);

ALTER TABLE OUTGOING
	ADD
		CONSTRAINT FK_ORDR_TO_OUTGOING
		FOREIGN KEY (
			ORDR_ID,
			PRODUCT_ID
		)
		REFERENCES ORDR (
			ORDR_ID,
			PRODUCT_ID
		);

ALTER TABLE PURCHASE
	ADD
		CONSTRAINT FK_PRODUCT_TO_PURCHASE
		FOREIGN KEY (
			PRODUCT_ID
		)
		REFERENCES PRODUCT (
			PRODUCT_ID
		);

ALTER TABLE INCOMING
	ADD
		CONSTRAINT FK_PURCHASE_TO_INCOMING
		FOREIGN KEY (
			PURCHASE_ID
		)
		REFERENCES PURCHASE (
			PURCHASE_ID
		);